services:
  postgres:
    image: postgres:15-alpine
    container_name: wallet-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - wallet-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d wallet"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  wallet-app:
    build: .
    container_name: wallet-app
    ports:
      - "${APP_PORT}:8080"
    environment:
      #DATASOURCE
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}

      #HikariCP
      DB_POOL_MAX_SIZE: ${DB_POOL_MAX_SIZE}
      DB_POOL_MIN_IDLE: ${DB_POOL_MIN_IDLE}
      DB_CONNECTION_TIMEOUT: ${DB_CONNECTION_TIMEOUT}
      DB_IDLE_TIMEOUT: ${DB_IDLE_TIMEOUT}
      DB_MAX_LIFETIME: ${DB_MAX_LIFETIME}
      DB_LEAK_DETECTION: ${DB_LEAK_DETECTION}

      #Retry
      WALLET_RETRY_MAX_ATTEMPTS: ${WALLET_RETRY_MAX_ATTEMPTS}
      WALLET_RETRY_DELAY: ${WALLET_RETRY_DELAY}
      WALLET_RETRY_MULTIPLIER: ${WALLET_RETRY_MULTIPLIER}
      WALLET_RETRY_MAX_DELAY: ${WALLET_RETRY_MAX_DELAY}

      #Hibernate
      HIBERNATE_BATCH_SIZE: ${HIBERNATE_BATCH_SIZE}
      HIBERNATE_FETCH_SIZE: ${HIBERNATE_FETCH_SIZE}
      HIBERNATE_SHOW_SQL: ${HIBERNATE_SHOW_SQL}
      HIBERNATE_FORMAT_SQL: ${HIBERNATE_FORMAT_SQL}

      #Liquibase
      SPRING_LIQUIBASE_ENABLED: ${LIQUIBASE_ENABLED}
      SPRING_LIQUIBASE_CHANGE_LOG: ${LIQUIBASE_CHANGE_LOG}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - wallet-network
    restart: unless-stopped

networks:
  wallet-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
    labels:
      com.wallet.description: "PostgreSQL data volume"